# Dragon Quest III Remake - Main Build Script
# PowerShell build system based on FFMQ-Info structure
# Builds ROM from disassembled source code

[CmdletBinding()]
param(
	[Parameter(HelpMessage = "Clean build directory before building")]
	[switch]$Clean,

	[Parameter(HelpMessage = "Only check tools and configuration")]
	[switch]$Check,

	[Parameter(HelpMessage = "Verbose build output")]
	[switch]$VerboseOutput,

	[Parameter(HelpMessage = "Skip ROM validation after build")]
	[switch]$SkipValidation
)

# Configuration
$ErrorActionPreference = 'Stop'
$ProjectRoot = $PSScriptRoot

# Project information
$ProjectName = "DQ3R"
$ProjectVersion = "1.0.0"
$TargetROM = "Dragon Quest III - Soshite Densetsu he... (J).smc"

# Helper functions
function Write-Success {
	param([string]$Message)
	Write-Host "✅ $Message" -ForegroundColor Green
}

function Write-Info {
	param([string]$Message)
	Write-Host "ℹ️  $Message" -ForegroundColor Cyan
}

function Write-Warning {
	param([string]$Message)
	Write-Host "⚠️  $Message" -ForegroundColor Yellow
}

function Write-Error {
	param([string]$Message)
	Write-Host "❌ $Message" -ForegroundColor Red
}

function Write-Section {
	param([string]$Title)
	Write-Host ""
	Write-Host "═══ $Title ═══" -ForegroundColor Magenta
	Write-Host ""
}

# Display build header
Write-Host ""
Write-Host "DQ3R Build System v$ProjectVersion" -ForegroundColor Cyan
Write-Host "================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Target: $TargetROM" -ForegroundColor Green
Write-Host "Mode: $(if ($Clean) { 'Clean Build' } elseif ($Check) { 'Check Only' } else { 'Incremental Build' })" -ForegroundColor Yellow
Write-Host "Started: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')" -ForegroundColor Gray
Write-Host ""

# Load build configuration
Write-Section "Loading Build Configuration"

$configPath = Join-Path $ProjectRoot "build.config.json"
if (Test-Path $configPath) {
	try {
		$config = Get-Content $configPath | ConvertFrom-Json
		Write-Success "Build configuration loaded: $configPath"
	} catch {
		Write-Error "Failed to parse build configuration: $_"
		exit 1
	}
} else {
	Write-Warning "Build configuration not found, using defaults"
	$config = @{
		build = @{
			mainSource = "src\asm\main.asm"
			outputRom = "build\dq3r-rebuilt.sfc"
			tempDir = "build\temp"
		}
	}
}

# Check required tools
Write-Section "Checking Required Tools"

# Check Asar assembler
try {
	$asarVersion = asar --version 2>&1
	if ($LASTEXITCODE -eq 0) {
		Write-Success "Asar assembler: $asarVersion"
	} else {
		throw "Asar not found"
	}
} catch {
	Write-Error "Asar SNES assembler not found"
	Write-Host "Download from: https://github.com/RPGHacker/asar/releases"
	exit 1
}

# Check Python
try {
	$pythonVersion = python --version 2>&1
	if ($LASTEXITCODE -eq 0) {
		Write-Success "Python: $pythonVersion"
	} else {
		throw "Python not found"
	}
} catch {
	Write-Warning "Python not found - some features may be unavailable"
}

# Check source ROM
$sourceRomPath = Join-Path $ProjectRoot "static\$TargetROM"
if (Test-Path $sourceRomPath) {
	$sourceRomSize = (Get-Item $sourceRomPath).Length
	Write-Success "Source ROM: $TargetROM ($([math]::Round($sourceRomSize/1KB, 1)) KB)"
} else {
	Write-Warning "Source ROM not found: $sourceRomPath"
	Write-Host "This is normal for initial setup - source ROM is only needed for comparison"
}

if ($Check) {
	Write-Section "Tool Check Complete"
	Write-Success "All required tools are available"
	Write-Host "Ready to build DQ3R ROM! 🎮"
	exit 0
}

# Setup build directories
Write-Section "Preparing Build Environment"

$buildDir = Join-Path $ProjectRoot $config.build.outputRom | Split-Path
$tempDir = Join-Path $ProjectRoot $config.build.tempDir

# Clean build if requested
if ($Clean -and (Test-Path $buildDir)) {
	Write-Host "Cleaning build directory..." -ForegroundColor Cyan
	Remove-Item $buildDir -Recurse -Force
}

# Create build directories
foreach ($dir in @($buildDir, $tempDir)) {
	if (-not (Test-Path $dir)) {
		Write-Host "Creating directory: $dir" -ForegroundColor Cyan
		New-Item -ItemType Directory -Path $dir -Force | Out-Null
	}
}

Write-Success "Build environment ready"

# Check for main source file
Write-Section "Checking Source Files"

$mainSourcePath = Join-Path $ProjectRoot $config.build.mainSource
if (Test-Path $mainSourcePath) {
	Write-Success "Main source file: $($config.build.mainSource)"
} else {
	Write-Warning "Main source file not found: $mainSourcePath"
	Write-Host ""
	Write-Host "Creating placeholder main source file..." -ForegroundColor Cyan

	# Create basic main.asm file
	$mainAsmContent = @"
; DQ3R (Dragon Quest III Remake) - Main Assembly File
; SNES 65816 Assembly - Main entry point for ROM building
; Generated by build.ps1

; Project: Dragon Quest III Disassembly
; Target Platform: Super Nintendo Entertainment System (SNES)
; Processor: 65816 (16-bit)

; Include header and configuration
.include "include/snes.inc"
.include "include/dq3r.inc"

; ROM header and configuration
.ifdef LOROM
	.orgh `$008000
.else
	.orgh `$000000
.endif

; Main ROM sections
.include "data/header.asm"       ; ROM header and title
.include "asm/boot.asm"          ; Boot and initialization code
.include "asm/engine.asm"        ; Game engine core
.include "asm/graphics.asm"      ; Graphics routines
.include "asm/sound.asm"         ; Sound and music
.include "asm/data.asm"          ; Game data tables

; Placeholder - actual disassembly will replace this
nop
nop
nop

; End of ROM marker
.pad `$400000
"@

	$mainAsmContent | Out-File -FilePath $mainSourcePath -Encoding UTF8
	Write-Success "Created placeholder: $($config.build.mainSource)"
}

# Attempt to build ROM
Write-Section "Building ROM"

$outputRomPath = Join-Path $ProjectRoot $config.build.outputRom

try {
	Write-Host "Assembling with Asar..." -ForegroundColor Cyan

	# Build Asar command line
	$asarArgs = @()

	if ($VerboseOutput) {
		$asarArgs += "-v"
	}

	# Add any additional Asar options
	$asarArgs += $mainSourcePath
	$asarArgs += $outputRomPath

	# Execute Asar
	$asarOutput = & asar @asarArgs 2>&1

	if ($LASTEXITCODE -eq 0) {
		Write-Success "ROM assembly completed successfully"

		# Check output ROM
		if (Test-Path $outputRomPath) {
			$builtRomSize = (Get-Item $outputRomPath).Length
			Write-Success "Output ROM: $($config.build.outputRom) ($([math]::Round($builtRomSize/1KB, 1)) KB)"
		} else {
			throw "Output ROM file not created"
		}
	} else {
		throw "Asar assembly failed with exit code $LASTEXITCODE"
	}

} catch {
	Write-Error "Build failed: $_"
	Write-Host ""
	Write-Host "Build output:" -ForegroundColor Yellow
	if ($asarOutput) {
		$asarOutput | ForEach-Object { Write-Host "  $_" -ForegroundColor Gray }
	}
	Write-Host ""
	Write-Host "Troubleshooting:" -ForegroundColor Yellow
	Write-Host "  • Check for syntax errors in assembly files" -ForegroundColor White
	Write-Host "  • Verify all include files exist" -ForegroundColor White
	Write-Host "  • Check for label conflicts or missing labels" -ForegroundColor White
	Write-Host "  • Review Asar documentation for error codes" -ForegroundColor White
	exit 1
}

# ROM validation (if not skipped)
if (-not $SkipValidation -and (Test-Path $outputRomPath)) {
	Write-Section "ROM Validation"

	# Basic size check
	$builtRomSize = (Get-Item $outputRomPath).Length

	# Common SNES ROM sizes (in bytes)
	$validSizes = @(512*1024, 1024*1024, 2048*1024, 3072*1024, 4096*1024)

	if ($validSizes -contains $builtRomSize) {
		Write-Success "ROM size is valid: $([math]::Round($builtRomSize/1KB, 1)) KB"
	} else {
		Write-Warning "ROM size unusual: $([math]::Round($builtRomSize/1KB, 1)) KB"
		Write-Host "Common SNES sizes: 512KB, 1MB, 2MB, 3MB, 4MB"
	}

	# Compare with source ROM if available
	if (Test-Path $sourceRomPath) {
		$sourceRomSize = (Get-Item $sourceRomPath).Length
		if ($builtRomSize -eq $sourceRomSize) {
			Write-Success "ROM size matches source: $([math]::Round($sourceRomSize/1KB, 1)) KB"
		} else {
			Write-Warning "ROM size differs from source"
			Write-Host "  Source: $([math]::Round($sourceRomSize/1KB, 1)) KB"
			Write-Host "  Built:  $([math]::Round($builtRomSize/1KB, 1)) KB"
		}
	}
}

# Build summary
Write-Section "Build Complete"

$buildTime = (Get-Date) - (Get-Date "$(Get-Date -Format 'yyyy-MM-dd') $(Get-Date -Format 'HH:mm:ss')")
Write-Success "DQ3R ROM build completed successfully!"
Write-Host ""
Write-Host "Build Summary:" -ForegroundColor Yellow
Write-Host "  Input:  $($config.build.mainSource)" -ForegroundColor White
Write-Host "  Output: $($config.build.outputRom)" -ForegroundColor White
Write-Host "  Size:   $([math]::Round($builtRomSize/1KB, 1)) KB" -ForegroundColor White
Write-Host "  Time:   $($buildTime.TotalSeconds.ToString('F1')) seconds" -ForegroundColor White
Write-Host ""
Write-Host "Next Steps:" -ForegroundColor Yellow
Write-Host "  • Test in emulator: MesenS, bsnes, etc." -ForegroundColor White
Write-Host "  • Run validation: python tools\validate_rom.py" -ForegroundColor White
Write-Host "  • Compare with original: python tools\compare_roms.py" -ForegroundColor White
Write-Host ""
Write-Host "Happy ROM hacking! 🎮✨" -ForegroundColor Cyan
