; Dragon Quest III - Battle System Disassembly
; Generated by Battle System Analyzer

; Random number generation (calculation phase)
rng_func_af3e:		; $af3e
	sec				 
	jsr $a5eb		   
	asl				 
	jsr $9822		   
	clc				 
	adc #$18			
	clc				 
	lsr				 
	lsr				 
	adc #$1c			
	and #$c0			
	sta $2a88		   
	rts				 

