; Dragon Quest III - Battle System Disassembly
; Generated by Battle System Analyzer

; Random number generation (calculation phase)
rng_func_AF3E:		; $AF3E
	sec                 
	jsr $a5eb           
	asl                 
	jsr $9822           
	clc                 
	adc #$18            
	clc                 
	lsr                 
	lsr                 
	adc #$1c            
	and #$c0            
	sta $2a88           
	rts                 

