;==============================================================================
; SystemBootEntry
; Type: General Purpose
; Address: $FF0000
; Size: 200 bytes
; Instructions: 50
;==============================================================================
;==============================================================================
SystemBootEntry:
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
	SBC				  ; FF FF FF FF | Subtract with carry (absolute long,X)
