; Dragon Quest III - Audio System Disassembly
; Generated by Audio System Analyzer

; Audio driver interface (driver)
audio_func_d8aa:		; $d8aa
	lda #$aa			
	bne #$fb			
	jsr $cca9		   
	bra #$26			
	lda #$00			
	bra #$0b			
	bne #$fb			
	jsr $408d		   

; APU communication (communication)
audio_func_d8e1:		; $d8e1
	jsr $50b7		   
	sta $2142		   
	jsr $01e0		   
	lda #$00			
	sta $2141		   
	sta $2140		   

; General audio operation (general)
audio_func_f57a:		; $f57a
	bra #$97			
	bra #$88			
	jmp $7980		   
	bra #$28			
	sty $4102		   
	rts				 

; APU communication (communication)
audio_func_c7fb:		; $c7fb
	sta $2140		   

