; Dragon Quest III - Audio System Disassembly
; Generated by Audio System Analyzer

; Audio driver interface (driver)
audio_func_D8AA:		; $D8AA
	lda #$aa            
	bne #$fb            
	jsr $cca9           
	bra #$26            
	lda #$00            
	bra #$0b            
	bne #$fb            
	jsr $408d           

; APU communication (communication)
audio_func_D8E1:		; $D8E1
	jsr $50b7           
	sta $2142           
	jsr $01e0           
	lda #$00            
	sta $2141           
	sta $2140           

; General audio operation (general)
audio_func_F57A:		; $F57A
	bra #$97            
	bra #$88            
	jmp $7980           
	bra #$28            
	sty $4102           
	rts                 

; APU communication (communication)
audio_func_C7FB:		; $C7FB
	sta $2140           

