; Dragon Quest III - Main Assembly File
; Generated by Advanced SNES Disassembler
; Total ROM size: 6,291,456 bytes
; Code regions: 4

.MEMORYMAP
SLOTSIZE $8000
DEFAULTSLOT 0
SLOT 0 $8000
.ENDME

.ROMBANKSIZE $8000
.ROMBANKS 128

.LOROM

.INCLUDE "bank_01.asm"
.INCLUDE "bank_02.asm"
.INCLUDE "bank_03.asm"
.INCLUDE "bank_04.asm"
