; Dragon Quest III - Graphics Engine Disassembly
; Generated by Graphics Engine Analyzer

; Display control
gfx_func_84be:		; $84be
	lda #$40            
	bne #$f4            
	lda #$01            
	lda #$8f            
	sta $2100           
	jsr $0589           
	jsr $0514           
	lda #$81            
	sta $4200           
	lda #$01            
	sta $7fe4           
	lda #$00            
	beq #$7f            

; General graphics operation
gfx_func_86b7:		; $86b7
	lda $7f7c           
	sta $7f7d           
	lda $7f7b           
	sta $7f7c           
	lda $7f7a           
	sta $7f7b           
	sta $7f7a           
	lda $7f7a           
	beq #$03            
	rts                 

; VRAM data transfer
gfx_func_88f0:		; $88f0
	sta $2116           
	sta $4302           
	beq #$19            
	sta $4305           
	sta $2116           
	sta $4302           
	beq #$19            
	sta $4305           
	sta $2116           
	sta $4302           
	beq #$19            
	sta $4305           
	sta $2116           
	bra #$e5            
	sta $4302           
	beq #$19            
	sta $4305           
	sta $2116           
	sta $4302           
	beq #$19            
	sta $4305           
	sta $2116           
	sta $4302           
	beq #$19            
	sta $4305           
	sta $2116           
	sta $4302           
	beq #$19            
	sta $4305           
	sta $2116           
	; ... (22 more instructions)

; General graphics operation
gfx_func_8c98:		; $8c98
	jmp $8c70           
	bne #$03            
	jmp $8d10           
	jmp $8cca           

; General graphics operation
gfx_func_a4ab:		; $a4ab
	rts                 

; General graphics operation
gfx_func_84ad:		; $84ad
	lda $6456           
	jsr $8d98           
	sta $211b           
	sta $211c           
	lda $2135           
	sta $211b           
	sta $211b           
	sta $211c           
	lda $2135           
	sta $211b           
	sta $211b           
	sta $211c           
	lda $2135           
	jsr $7aab           
	lda $647a           
	lda $6474           
	jsr $1b8d           
	sta $211b           
	sta $211c           
	sta $211b           
	sta $211b           
	sta $211c           
	sta $211b           
	sta $211b           
	sta $211c           
	sta $211b           
	sta $211b           
	sta $211c           
	jsr $7aa5           
	lda $6478           
	; ... (30 more instructions)

; General graphics operation
gfx_func_850d:		; $850d
	lda $647a           
	lda $6474           
	jsr $1b8d           
	sta $211b           
	sta $211c           
	sta $211b           
	sta $211b           
	sta $211c           
	sta $211b           
	sta $211b           
	sta $211c           
	sta $211b           
	sta $211b           
	sta $211c           
	jsr $7aa5           
	lda $6478           
	lda $6472           
	jsr $1b8d           
	sta $211b           
	sta $211c           
	sta $211b           
	sta $211b           
	sta $211c           
	sta $211b           
	sta $211b           
	sta $211c           
	sta $211b           
	sta $211b           
	sta $211c           
	jsr $7aa5           
	; ... (16 more instructions)

; General graphics operation
gfx_func_8589:		; $8589
	lda $6478           
	lda $6472           
	jsr $1b8d           
	sta $211b           
	sta $211c           
	sta $211b           
	sta $211b           
	sta $211c           
	sta $211b           
	sta $211b           
	sta $211c           
	sta $211b           
	sta $211b           
	sta $211c           
	jsr $7aa5           
	lda $647c           
	lda $6476           
	jsr $1b8d           
	sta $211b           
	sta $211c           
	sta $211b           
	sta $211b           
	sta $211c           
	sta $211b           
	sta $211b           
	sta $211c           
	sta $211b           
	sta $211b           
	sta $211c           
	jsr $7aa5           
	; ... (1 more instructions)

; General graphics operation
gfx_func_8605:		; $8605
	lda $647c           
	lda $6476           
	jsr $1b8d           
	sta $211b           
	sta $211c           
	sta $211b           
	sta $211b           
	sta $211c           
	sta $211b           
	sta $211b           
	sta $211c           
	sta $211b           
	sta $211b           
	sta $211c           
	jsr $7aa5           
	rts                 

; General graphics operation
gfx_func_8e53:		; $8e53
	lda $62a0           
	lda #$ac            
	lda #$7e            
	lda #$6c            
	lda #$7e            
	lda $62aa           
	jsr $1b8d           
	sta $211b           
	sta $211c           
	jsr $35ad           
	jsr $1b8d           
	sta $211b           
	sta $211c           
	jsr $35ad           

; Display control
gfx_func_dc6d:		; $dc6d
	sta $2100           
	lda #$0c            

; General graphics operation
gfx_func_f55c:		; $f55c
	bra #$d2            
	jsr $c108           
	sta $2112           
	rts                 

; General graphics operation
gfx_func_868f:		; $868f
	bne #$d0            
	bne #$bf            
	bne #$d0            
	bne #$c8            
	bne #$4b            
	bne #$dc            
	bne #$c1            
	bne #$c8            
	rts                 

; General graphics operation
gfx_func_9ef2:		; $9ef2
	jmp $5140           
	sta $2113           
	jmp $3b48           

; General graphics operation
gfx_func_f215:		; $f215
	jsr $4177           
	beq #$bf            
	lda $6f93           
	bra #$ff            
	bne #$00            
	beq #$af            
	jsr $6094           
	sta $2129           
	bne #$d8            
	sta $2900           
	bne #$00            
	bne #$00            
	bra #$7f            
	bra #$7f            
	bra #$ff            
	bra #$ff            

; Sprite/OAM management
gfx_func_a008:		; $a008
	lda #$80            
	sta $2100           
	lda #$00            
	sta $2101           
	sta $2102           
	sta $2103           
	sta $2105           
	sta $2106           
	sta $2107           
	sta $2108           
	sta $2109           
	sta $210a           
	sta $210b           
	sta $210c           
	sta $210d           
	sta $210d           
	sta $210e           
	sta $210e           
	sta $210f           
	sta $210f           
	sta $2110           
	sta $2110           
	sta $2111           
	sta $2111           
	sta $2112           
	sta $2112           
	sta $2113           
	sta $2113           
	sta $2114           
	sta $2114           
	; ... (94 more instructions)

